services:
  db:
    image: postgres:15
    container_name: postgres_coinedu
    environment:
      POSTGRES_DB: CoinEdu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_coinedu
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db  # Nome do serviço acima
      - REDIS_HOST=redis
      - DB_USER=user
      - DB_PASSWORD=password