spring:
  application:
    name: CoinEdu

  datasource:
    url: jdbc:postgresql://localhost:5432/coinedu
    driver-class-name: org.postgresql.Driver
    username: admin
    password: LucasGamer123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: http://localhost:9200

  cache:
    caffeine:
      cache-names=moeda,historico:
      spec=maximumSize=500,expireAfterWrite=5m:

  mail:
    host: smtp.gmail.com
    port: 587
    username: "adiciona o seu gmail"
    password: "Adiciona sua senha do app do gmail"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true